import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { TrendingUp, TrendingDown, Brain, Calendar, Target } from "lucide-react";

interface PredictionData {
  symbol: string;
  currentPrice: number;
  predictedPrice: number;
  confidence: number;
  timeframe: string;
  trend: "up" | "down";
  change: number;
  changePercent: number;
}

interface PredictionCardProps {
  prediction: PredictionData;
}

const PredictionCard = ({ prediction }: PredictionCardProps) => {
  const isPositive = prediction.trend === "up";
  
  return (
    <Card className="w-full max-w-2xl mx-auto shadow-card">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Brain className="h-6 w-6 text-primary" />
            AI Prediction for {prediction.symbol}
          </div>
          <Badge variant={isPositive ? "default" : "destructive"} className="text-sm">
            {isPositive ? "BULLISH" : "BEARISH"}
          </Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="grid grid-cols-2 gap-6">
          <div className="text-center">
            <p className="text-sm text-muted-foreground mb-1">Current Price</p>
            <p className="text-2xl font-bold text-primary">
              ${prediction.currentPrice.toFixed(2)}
            </p>
          </div>
          <div className="text-center">
            <p className="text-sm text-muted-foreground mb-1">Predicted Price</p>
            <p className={`text-2xl font-bold ${isPositive ? 'text-success' : 'text-destructive'}`}>
              ${prediction.predictedPrice.toFixed(2)}
            </p>
          </div>
        </div>

        <div className="bg-gradient-secondary rounded-lg p-4">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              {isPositive ? (
                <TrendingUp className="h-5 w-5 text-success" />
              ) : (
                <TrendingDown className="h-5 w-5 text-destructive" />
              )}
              <span className="font-semibold">Price Movement</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm text-muted-foreground">{prediction.timeframe}</span>
            </div>
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Expected Change</p>
              <p className={`text-lg font-bold ${isPositive ? 'text-success' : 'text-destructive'}`}>
                {isPositive ? '+' : ''}${prediction.change.toFixed(2)}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Percentage</p>
              <p className={`text-lg font-bold ${isPositive ? 'text-success' : 'text-destructive'}`}>
                {isPositive ? '+' : ''}{prediction.changePercent.toFixed(2)}%
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between p-4 bg-primary/5 rounded-lg">
          <div className="flex items-center gap-2">
            <Target className="h-5 w-5 text-primary" />
            <span className="font-semibold">AI Confidence</span>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-24 bg-muted rounded-full h-2">
              <div 
                className="bg-gradient-accent h-2 rounded-full transition-all duration-500"
                style={{ width: `${prediction.confidence}%` }}
              />
            </div>
            <span className="font-bold text-primary">{prediction.confidence}%</span>
          </div>
        </div>

        <div className="text-xs text-muted-foreground text-center">
          This prediction is generated by AI and should not be considered as financial advice. 
          Always do your own research before making investment decisions.
        </div>
      </CardContent>
    </Card>
  );
};

export default PredictionCard;